### ISSUE TITLE
Flaky test: Used Resource Cleaned Up By Reaper

### ISSUE THREAD

**Issue by rossabaker** [typelevel/keypool#229]
https://github.com/typelevel/keypool/pull/228/checks?check_run_id=3044490089#step:9:27

**Comment by rossabaker** [comment]
[Still happens now and then](https://github.com/typelevel/keypool/runs/5167889438?check_suite_focus=true)

**Comment by danicheg** [comment]
This strikes [again](https://github.com/typelevel/keypool/runs/7056624904?check_suite_focus=true#step:9:43)
