### ISSUE TITLE
Build a KeyPoll with Resource

### ISSUE THREAD

**Issue by AL333Z** [typelevel/keypool#248]
Hi, I see the builder is expecting a `create` and a `destroy` fn, which is pretty much the shape of a `Resource`.
```scala
object KeyPoolBuilder {
  def apply[F[_]: Temporal, A, B](
    create: A => F[B],
    destroy: B => F[Unit]
  ): KeyPoolBuilder[F, A, B] = ???
}
```

Since Resource is great for its composability, I wonder how hard it would be to have a variant taking a Resource instead, like:
```scala
object KeyPoolBuilder {
  def apply[F[_]: Temporal, A, B](
    resource: A => Resource[F, B]
  ): KeyPoolBuilder[F, A, B] = ???
}
```

This may be really useful when the Resource in the pool is requiring several intermediate resources to get acquired or when we interact with libs exposing resources.

Thanks

**Comment by rossabaker** [comment]
This seems reasonable to me.  I guess we'd have to pull apart the `Resource` with `allocated` to fill in the `???`?

**Comment by AL333Z** [comment]
Yep, that's my guess as well.
I think I'll give it a try and submit a PR as soon as I come up with something decent.
