### ISSUE TITLE
Pool allows borrowing more resources than allowed

### ISSUE THREAD

**Issue by iRevive** [typelevel/keypool#389]
## The problem

**keypool version:** 0.4.7, main

The `keypool` allows borrowing more resources than allowed by the config.

## Use case

I am working on an application that uses TCP connections for communication with external services. 
I would like to have a bound pool of `N` reusable connections.

Currently, it's not possible. The application allocates as many connections as it can. 
I would expect to have `pool.take` back-pressured when the pool is full (`open resources == maxTotal`).

## Test

Let's make a pool with the capacity of `1` and take `2` resources from it for an infinite time. 

```scala
test("does not allocate more resources than allowed") {
  Pool
    .Builder(
      Ref.of[IO, Int](1),
      nothing
    )
    .withMaxTotal(1)
    .build
    .use { pool =>
      for {
        counter <- IO.ref(0)
        _ <- pool.take.use(_ => counter.update(_ + 1) >> IO.never).start
        _ <- pool.take.use(_ => counter.update(_ + 1) >> IO.never).start
        _ <- IO.sleep(1.second)
        acquired <- counter.get
      } yield assert(acquired === 1) // currently, acquired == 2
    }
}
```

## Other implementations

A `GenericObjectPool` from Apache commons does not allow borrowing more objects than the limit.

https://scastie.scala-lang.org/bjFZbgFCTta4ic4XNckh2Q

**Comment by rossabaker** [comment]
I agree.  There must be a hard limit.

**Comment by ChristopherDavenport** [comment]
This was the design on purpose not a bug. This was about the pool, not what others had access to. This should default to a higher number or give a massive warning as this could cripple servers relying on more connections in use. 

If this is released as a patch you will break people when they upgrade.

**Comment by rossabaker** [comment]
Alright, it's a big enough semantic change, I guess we shouldn't do it in 0.4.  But the `maxTotal` behavior under that name will surprise nearly everyone.  That name is the hard limit in Apache HTTP Client, Jetty, Blaze, and anything derived from Commons-Pool.  There are also similarly named hard limits on async-http-client (`maxConnections`), okhttp (`maxRequests`), and akka-http (`maxOpenRequests`).  JDK11's HTTP client is the only pool I can think of that does not limit connections.

**Comment by ChristopherDavenport** [comment]
This change is good assuming it doesn't lead to deadlocks. Just shouldn't silently break people who might be relying on the former behavior.

**Comment by rossabaker** [comment]
Yes, `new.maxIdle == old.maxTotal` and `new.maxTotal == Int.MaxValue` should behave the same.  Because we redefined the `maxTotal` name, there's no way to avoid a quiet semantic change between 0.4 and 0.5.  If 0.5 breaks bincompat, downstream (most notably Ember) is stuck.  If 0.5 maintains bincompat, then Ember et al are forced to think about a jump.  We might be able to smooth 0.4->0.5 if we deprecate `maxTotal` as an alias for `maxIdle`, and establish a new name like `maxOpen` for the new feature.

I forked off a series/0.4 from before the merge, just in case.  I am not adding it to Typelevel Steward until it's more clear we have to maintain it.

**Comment by armanbilge** [comment]
Not the right place for this discussion, but I think there is an argument that ember should be schismed as well. There's no reason it and its dependencies have to be subject to the far more important bincompat constraints on http4s-core,server,client etc.
